-- ═══════════════════════════════════════════════════════════════
-- Configuración persistente por coach (normativos, tablas, etc.)
-- Ejecutar en Supabase SQL Editor
-- ═══════════════════════════════════════════════════════════════

create table if not exists public.coach_settings (
  id            bigint generated by default as identity primary key,
  coach_id      uuid        not null references auth.users(id) on delete cascade,
  setting_key   text        not null,
  setting_value jsonb       not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (coach_id, setting_key)
);

alter table public.coach_settings enable row level security;

create policy if not exists "coach_settings_owner_all" on public.coach_settings
  using (auth.uid() = coach_id)
  with check (auth.uid() = coach_id);

create index if not exists coach_settings_coach_idx
  on public.coach_settings (coach_id);

create index if not exists coach_settings_key_idx
  on public.coach_settings (setting_key);
